@startuml UniversityDiagram

class Universite {

}

class Sinif {
    
}


class Departman {
    
}

class Ofis {
    
}

class Calisanlar {
    
}

class Profesor {
    
}

class Memur {
    
}

Universite "1" -- "0..*" Ofis
Universite "1" -- "1..*" Departman 
Universite "1" -- "0..*" Sinif  

Departman "1" -- "1..*" Ofis 

Universite "1" -- "0..*" Calisanlar

Calisanlar "1" -- "1" Ofis

Calisanlar <|-- Profesor
Calisanlar <|-- Memur

@enduml
